project_id = "seller"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.migrations]
enabled = true
schema_paths = ["./migrations/*.sql"]

[db.seed]
enabled = false

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "25MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000", "http://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[functions]
enabled = true
verify_jwt = true
